@host=https://localhost:7264

POST {{host}}/auth/courier/register
#Change Bearer - when testing after reboot
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZWEzYmFkNS1jNzkxLTQ5NWQtYmEyMi01MWUxZWU4MGFlOTUiLCJnaXZlbl9uYW1lIjoiSmFrdWIiLCJmYW1pbHlfbmFtZSI6Ik1hY2llamV3c2tpIiwianRpIjoiMmE1N2M0OTktMTRiYi00NzM0LWE1ZWYtZGZlNTM3NWU1OWYxIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYXRvciIsImV4cCI6MTY3MTIxNDYyMCwiaXNzIjoiRGVsaXZlcnlDb21wYW55IiwiYXVkIjoiRGVsaXZlcnlDb21wYW55In0.xVra9n6h33GHdgbfCQ8-5ewSTq5n1b10onlENZY-Oe4
Content-Type: application/json

{
    "firstName": "Jakub",
    "lastName": "Maciejewski",
    "email": "jakubm55555@gmail.com",
    "password": "Jakub1232!",
    "dateBirth": "2001-04-28",
    "address": "Grójecka 39 Warszawa"
}
### After this triple hashtags we can create another requests