@host=https://localhost:7264

POST {{host}}/manageclientorder/client/cancel
#Change Bearer - when testing after reboot
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlODhkMTY2Ni1kM2Y5LTQ4NzUtOTUzZS01ODg1M2MwYzE4ZWQiLCJnaXZlbl9uYW1lIjoiSmFrdWIiLCJmYW1pbHlfbmFtZSI6Ik1hY2llamV3c2tpIiwianRpIjoiNTQxMDc0YWMtZjFjMS00YTNhLWI2ZDEtN2IwNGYyYTUzMTBkIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQ2xpZW50IiwiZXhwIjoxNjcyMjIwNjgyLCJpc3MiOiJEZWxpdmVyeUNvbXBhbnkiLCJhdWQiOiJEZWxpdmVyeUNvbXBhbnkifQ.XGm46tY7WGC3AL5WsuWCfQSZO0XGS8h1S-_t-0AnJgA
Content-Type: application/json

{
    "orderId": "6e5f9f84-ba28-4fbb-97bc-1bf2bf09ae49"
}
### After this triple hashtags we can create another requests