@host=https://localhost:7264

POST {{host}}/manageclientorder/client/create
#Change Bearer - when testing after reboot
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyZGVhMjdhYS01MTY2LTQ5MzItYTQzZC00ZjBkMTc0MmM3M2MiLCJnaXZlbl9uYW1lIjoiSmFrdWIiLCJmYW1pbHlfbmFtZSI6Ik1hY2llamV3c2tpIiwianRpIjoiY2ZiZmNlYTUtMDU3Ny00YWU4LTk4ZTEtMGIwMDNlYWY2YmI2IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQ2xpZW50IiwiZXhwIjoxNjcyMTc3NDQyLCJpc3MiOiJEZWxpdmVyeUNvbXBhbnkiLCJhdWQiOiJEZWxpdmVyeUNvbXBhbnkifQ.dvZ5gxVaRFWSxxycSSHXtGpsVhrBhRY_oFxaMeL8OZM
Content-Type: application/json

{
    "addressSent": "1 Maja 34 Sosnowiec",
    "addressDelivery": "Grójecka 39 Warszawa",
    "name": "MojaPrzesylka1",
    "sizeName": "Small",
    "dateSent": "2022-04-28",
    "dateDelivery": "2001-04-30"
}
### After this triple hashtags we can create another requests