@host=https://localhost:7264

GET  {{host}}/manageclientorder/client/getall
#Change Bearer - when testing after reboot
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3NTQ0Y2FhZC1hNmY3LTQyMDItOWUxNS1mNTgwN2VlMWM2NDIiLCJnaXZlbl9uYW1lIjoiSmFrdWIiLCJmYW1pbHlfbmFtZSI6Ik1hY2llamV3c2tpIiwianRpIjoiZWFmZjA4MmYtMTM4Ni00MmVhLTgzZjUtMjJlY2NmNDM2YmI0IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQ2xpZW50IiwiZXhwIjoxNjcyMjI4ODMyLCJpc3MiOiJEZWxpdmVyeUNvbXBhbnkiLCJhdWQiOiJEZWxpdmVyeUNvbXBhbnkifQ.qMw62NXaorUGTsIM_jsFxxtGjwKFhU9labr12yklBDI

### After this triple hashtags we can create another requests